repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        files: ^src/.*\.(ts|tsx|js|css|html|json)$|^media/.*\.(ts|tsx|js|css|html|json)
        args: ['--config=./.prettierrc', '--ignore-path=./.prettierignore']
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: 'v8.33.0'
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint
          - typescript
          - '@typescript-eslint/parser'
          - '@typescript-eslint/eslint-plugin'
          - eslint-config-prettier
          - eslint-plugin-prettier
        files: ^src/.*\.[jt]sx?$
        types: [file]
        args: ['--config=./.eslintrc.json', '--ignore-path=./.eslintignore']
